# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/Snapchat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61ta/Snapchat.proto\"H\n\x04root\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x19\n\x07\x43ontent\x18\x04 \x02(\x0b\x32\x08.content\x12\x19\n\ntimestamps\x18\x06 \x01(\x0b\x32\x05.time\"%\n\x04time\x12\x0f\n\x07\x63reated\x18\x01 \x02(\x04\x12\x0c\n\x04read\x18\x02 \x01(\x04\"A\n\x07\x63ontent\x12\x17\n\x04\x63hat\x18\x04 \x01(\x0b\x32\t.content2\x12\x1d\n\nstartMedia\x18\x05 \x01(\x0b\x32\t.content2\"Z\n\x08\x63ontent2\x12\x1a\n\x0b\x63hatMessage\x18\x02 \x01(\x0b\x32\x05.text\x12\x17\n\x07unknown\x18\x01 \x01(\x0b\x32\x06.fill1\x12\x19\n\tmediatext\x18\x07 \x01(\x0b\x32\x06.fill1\"<\n\x05\x66ill1\x12\x17\n\x07unknown\x18\x03 \x01(\x0b\x32\x06.fill2\x12\x1a\n\nmediatext2\x18\x0b \x01(\x0b\x32\x06.media\" \n\x05\x66ill2\x12\x17\n\x07unknown\x18\x02 \x01(\x0b\x32\x06.media\"0\n\x05media\x12\x0f\n\x07\x63\x61\x63heId\x18\x02 \x01(\t\x12\x16\n\x0emediatextFinal\x18\x01 \x01(\t\"\x17\n\x04text\x12\x0f\n\x07message\x18\x01 \x01(\t')



_ROOT = DESCRIPTOR.message_types_by_name['root']
_TIME = DESCRIPTOR.message_types_by_name['time']
_CONTENT = DESCRIPTOR.message_types_by_name['content']
_CONTENT2 = DESCRIPTOR.message_types_by_name['content2']
_FILL1 = DESCRIPTOR.message_types_by_name['fill1']
_FILL2 = DESCRIPTOR.message_types_by_name['fill2']
_MEDIA = DESCRIPTOR.message_types_by_name['media']
_TEXT = DESCRIPTOR.message_types_by_name['text']
root = _reflection.GeneratedProtocolMessageType('root', (_message.Message,), {
  'DESCRIPTOR' : _ROOT,
  '__module__' : 'data.Snapchat_pb2'
  # @@protoc_insertion_point(class_scope:root)
  })
_sym_db.RegisterMessage(root)

time = _reflection.GeneratedProtocolMessageType('time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'data.Snapchat_pb2'
  # @@protoc_insertion_point(class_scope:time)
  })
_sym_db.RegisterMessage(time)

content = _reflection.GeneratedProtocolMessageType('content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'data.Snapchat_pb2'
  # @@protoc_insertion_point(class_scope:content)
  })
_sym_db.RegisterMessage(content)

content2 = _reflection.GeneratedProtocolMessageType('content2', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT2,
  '__module__' : 'data.Snapchat_pb2'
  # @@protoc_insertion_point(class_scope:content2)
  })
_sym_db.RegisterMessage(content2)

fill1 = _reflection.GeneratedProtocolMessageType('fill1', (_message.Message,), {
  'DESCRIPTOR' : _FILL1,
  '__module__' : 'data.Snapchat_pb2'
  # @@protoc_insertion_point(class_scope:fill1)
  })
_sym_db.RegisterMessage(fill1)

fill2 = _reflection.GeneratedProtocolMessageType('fill2', (_message.Message,), {
  'DESCRIPTOR' : _FILL2,
  '__module__' : 'data.Snapchat_pb2'
  # @@protoc_insertion_point(class_scope:fill2)
  })
_sym_db.RegisterMessage(fill2)

media = _reflection.GeneratedProtocolMessageType('media', (_message.Message,), {
  'DESCRIPTOR' : _MEDIA,
  '__module__' : 'data.Snapchat_pb2'
  # @@protoc_insertion_point(class_scope:media)
  })
_sym_db.RegisterMessage(media)

text = _reflection.GeneratedProtocolMessageType('text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'data.Snapchat_pb2'
  # @@protoc_insertion_point(class_scope:text)
  })
_sym_db.RegisterMessage(text)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOT._serialized_start=23
  _ROOT._serialized_end=95
  _TIME._serialized_start=97
  _TIME._serialized_end=134
  _CONTENT._serialized_start=136
  _CONTENT._serialized_end=201
  _CONTENT2._serialized_start=203
  _CONTENT2._serialized_end=293
  _FILL1._serialized_start=295
  _FILL1._serialized_end=355
  _FILL2._serialized_start=357
  _FILL2._serialized_end=389
  _MEDIA._serialized_start=391
  _MEDIA._serialized_end=439
  _TEXT._serialized_start=441
  _TEXT._serialized_end=464
# @@protoc_insertion_point(module_scope)
